<?php
include "Personne.class.php";
$personne[]=new Personne (["Nom"=>"Rjeb","Prenom"=>"Zied","Age"=>29]);
$personne[]=new Personne (["Nom"=>"Rjeb","Prenom"=>"Julie","Age"=>24]);
$personne[]=new Personne (["Nom"=>"boilevin","Prenom"=>"Emilie","Age"=>42]);
$personne[]=new Personne (["Nom"=>"Rjeb","Prenom"=>"Lobna","Age"=>25]);
$personne[]=new Personne (["Nom"=>"Rjeb","Prenom"=>"Zied","Age"=>30]);
$personne[]=new Personne (["Nom"=>"Rjeb","Prenom"=>"Zied","Age"=>30]);
$personne[]=new Personne (["Nom"=>"Rjeb","Prenom"=>"Zied","Age"=>30]);
$personne[]=new Personne (["Nom"=>"Rjeb","Prenom"=>"Zied","Age"=>30]);
$personne[]=new Personne (["Nom"=>"Rjeb","Prenom"=>"Zied","Age"=>30]);
$personne[]=new Personne (["Nom"=>"Rjeb","Prenom"=>"Zied","Age"=>30]);
$personne[]=new Personne (["Nom"=>"Rjeb","Prenom"=>"Zied","Age"=>30]);
$personne[]=new Personne (["Nom"=>"Rjeb","Prenom"=>"Zied","Age"=>30]);
$personne[]=new Personne (["Nom"=>"Rjeb","Prenom"=>"Zied","Age"=>30]);
$personne[]=new Personne (["Nom"=>"Rjeb","Prenom"=>"Zied","Age"=>30]);
$personne[]=new Personne (["Nom"=>"Rjeb","Prenom"=>"Zied","Age"=>30]);
$personne[]=new Personne (["Nom"=>"Rjeb","Prenom"=>"Zied","Age"=>30]);
$personne[]=new Personne (["Nom"=>"Rjeb","Prenom"=>"Zied","Age"=>30]);
$personne[]=new Personne (["Nom"=>"Rjeb","Prenom"=>"Zied","Age"=>30]);
$personne[]=new Personne (["Nom"=>"Rjeb","Prenom"=>"Zied","Age"=>30]);
$personne[]=new Personne (["Nom"=>"Rjeb","Prenom"=>"Zied","Age"=>30]);
